//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.11.02 at 10:24:27 GMT+02:00 
//


package mats.importer;


/**
 * Java content class for Materials complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="Materials">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="material" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ownCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="matType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="matGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="matDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="colorRed" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="colorGreen" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="colorBlue" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="colorAlpha" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="materialImage" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                   &lt;element name="groupID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Materials {


    java.util.List getMaterial();


    /**
     * Java content class for annonymous complex type.
     *  <p>The following schema fragment specifies the expected content contained within this java content object.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ownCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="matType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="matGroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="matDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="colorRed" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="colorGreen" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="colorBlue" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="colorAlpha" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="materialImage" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *         &lt;element name="groupID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface MaterialType {


        java.lang.String getMatGroup();

        void setMatGroup(java.lang.String value);

        java.math.BigInteger getColorRed();

        void setColorRed(java.math.BigInteger value);

        java.math.BigInteger getColorBlue();

        void setColorBlue(java.math.BigInteger value);

        java.math.BigInteger getColorAlpha();

        void setColorAlpha(java.math.BigInteger value);

        java.math.BigInteger getGroupID();

        void setGroupID(java.math.BigInteger value);

        java.math.BigInteger getMatType();

        void setMatType(java.math.BigInteger value);

        byte[] getMaterialImage();

        void setMaterialImage(byte[] value);

        java.lang.String getOwnCode();

        void setOwnCode(java.lang.String value);

        java.lang.String getMatDesc();

        void setMatDesc(java.lang.String value);

        java.math.BigInteger getColorGreen();

        void setColorGreen(java.math.BigInteger value);

        java.lang.String getItemCode();

        void setItemCode(java.lang.String value);

    }

}
