//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.11.02 at 10:24:27 GMT+02:00 
//


package mats.importer;


/**
 * Java content class for materialDataType complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="materialDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="suppliers" type="{}Suppliers"/>
 *         &lt;element name="materialGroups" type="{}MaterialGroups"/>
 *         &lt;element name="materials" type="{}Materials"/>
 *         &lt;element name="values" type="{}Values"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface MaterialDataType {


    mats.importer.Materials getMaterials();

    void setMaterials(mats.importer.Materials value);

    mats.importer.MaterialGroups getMaterialGroups();

    void setMaterialGroups(mats.importer.MaterialGroups value);

    mats.importer.Suppliers getSuppliers();

    void setSuppliers(mats.importer.Suppliers value);

    mats.importer.Values getValues();

    void setValues(mats.importer.Values value);

}
