//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.11.02 at 10:24:27 GMT+02:00 
//


package mats.importer;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the mats.importer package. <p>An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups.  Factory methods for each of these are provided in this class.
 * 
 */
public class ObjectFactory
    extends com.sun.xml.bind.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap();

    static {
        defaultImplementations.put((mats.importer.MaterialGroups.class), (mats.importer.impl.MaterialGroupsImpl.class));
        defaultImplementations.put((mats.importer.Materials.MaterialType.class), (mats.importer.impl.MaterialsImpl.MaterialTypeImpl.class));
        defaultImplementations.put((mats.importer.MaterialGroups.MaterialGroupsType.class), (mats.importer.impl.MaterialGroupsImpl.MaterialGroupsTypeImpl.class));
        defaultImplementations.put((mats.importer.MaterialData.class), (mats.importer.impl.MaterialDataImpl.class));
        defaultImplementations.put((mats.importer.Suppliers.class), (mats.importer.impl.SuppliersImpl.class));
        defaultImplementations.put((mats.importer.Suppliers.SupplierType.class), (mats.importer.impl.SuppliersImpl.SupplierTypeImpl.class));
        defaultImplementations.put((mats.importer.Materials.class), (mats.importer.impl.MaterialsImpl.class));
        defaultImplementations.put((mats.importer.Values.ValueType.class), (mats.importer.impl.ValuesImpl.ValueTypeImpl.class));
        defaultImplementations.put((mats.importer.Values.class), (mats.importer.impl.ValuesImpl.class));
        defaultImplementations.put((mats.importer.MaterialDataType.class), (mats.importer.impl.MaterialDataTypeImpl.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mats.importer
     * 
     */
    public ObjectFactory() {
        super(new mats.importer.ObjectFactory.GrammarInfoImpl());
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface the Class object of the javacontent interface to instantiate
     * @return a new instance
     * @throws JAXBException if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name the name of the property to retrieve
     * @return the value of the requested property
     * @throws PropertyException when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name the name of the property to retrieve
     * @param value the value of the property to be set
     * @throws PropertyException when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of MaterialGroups
     * 
     * @throws JAXBException if an error occurs
     */
    public mats.importer.MaterialGroups createMaterialGroups()
        throws javax.xml.bind.JAXBException
    {
        return ((mats.importer.MaterialGroups) newInstance((mats.importer.MaterialGroups.class)));
    }

    /**
     * Create an instance of MaterialsMaterialType
     * 
     * @throws JAXBException if an error occurs
     */
    public mats.importer.Materials.MaterialType createMaterialsMaterialType()
        throws javax.xml.bind.JAXBException
    {
        return ((mats.importer.Materials.MaterialType) newInstance((mats.importer.Materials.MaterialType.class)));
    }

    /**
     * Create an instance of MaterialGroupsMaterialGroupsType
     * 
     * @throws JAXBException if an error occurs
     */
    public mats.importer.MaterialGroups.MaterialGroupsType createMaterialGroupsMaterialGroupsType()
        throws javax.xml.bind.JAXBException
    {
        return ((mats.importer.MaterialGroups.MaterialGroupsType) newInstance((mats.importer.MaterialGroups.MaterialGroupsType.class)));
    }

    /**
     * Create an instance of MaterialData
     * 
     * @throws JAXBException if an error occurs
     */
    public mats.importer.MaterialData createMaterialData()
        throws javax.xml.bind.JAXBException
    {
        return ((mats.importer.MaterialData) newInstance((mats.importer.MaterialData.class)));
    }

    /**
     * Create an instance of Suppliers
     * 
     * @throws JAXBException if an error occurs
     */
    public mats.importer.Suppliers createSuppliers()
        throws javax.xml.bind.JAXBException
    {
        return ((mats.importer.Suppliers) newInstance((mats.importer.Suppliers.class)));
    }

    /**
     * Create an instance of SuppliersSupplierType
     * 
     * @throws JAXBException if an error occurs
     */
    public mats.importer.Suppliers.SupplierType createSuppliersSupplierType()
        throws javax.xml.bind.JAXBException
    {
        return ((mats.importer.Suppliers.SupplierType) newInstance((mats.importer.Suppliers.SupplierType.class)));
    }

    /**
     * Create an instance of Materials
     * 
     * @throws JAXBException if an error occurs
     */
    public mats.importer.Materials createMaterials()
        throws javax.xml.bind.JAXBException
    {
        return ((mats.importer.Materials) newInstance((mats.importer.Materials.class)));
    }

    /**
     * Create an instance of ValuesValueType
     * 
     * @throws JAXBException if an error occurs
     */
    public mats.importer.Values.ValueType createValuesValueType()
        throws javax.xml.bind.JAXBException
    {
        return ((mats.importer.Values.ValueType) newInstance((mats.importer.Values.ValueType.class)));
    }

    /**
     * Create an instance of Values
     * 
     * @throws JAXBException if an error occurs
     */
    public mats.importer.Values createValues()
        throws javax.xml.bind.JAXBException
    {
        return ((mats.importer.Values) newInstance((mats.importer.Values.class)));
    }

    /**
     * Create an instance of MaterialDataType
     * 
     * @throws JAXBException if an error occurs
     */
    public mats.importer.MaterialDataType createMaterialDataType()
        throws javax.xml.bind.JAXBException
    {
        return ((mats.importer.MaterialDataType) newInstance((mats.importer.MaterialDataType.class)));
    }

    private static class GrammarInfoImpl
        extends com.sun.xml.bind.GrammarInfo
    {


        public java.lang.Class getDefaultImplementation(java.lang.Class javaContentInterface) {
            return ((java.lang.Class) defaultImplementations.get(javaContentInterface));
        }

        public java.lang.Class getRootElement(java.lang.String uri, java.lang.String local) {
            if (("" == uri)&&("materialData" == local)) {
                return (mats.importer.impl.MaterialDataImpl.class);
            }
            return null;
        }

        public java.lang.String[] getProbePoints() {
            return new java.lang.String[] {"", "materialData"};
        }

    }

}
