//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.11.02 at 10:24:27 GMT+02:00 
//


package mats.importer;


/**
 * Java content class for Values complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="Values">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="supplier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="thickness" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="rebate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Values {


    java.util.List getValue();


    /**
     * Java content class for annonymous complex type.
     *  <p>The following schema fragment specifies the expected content contained within this java content object.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="supplier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="thickness" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="rebate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ValueType {


        java.math.BigDecimal getCost();

        void setCost(java.math.BigDecimal value);

        java.lang.String getSupplier();

        void setSupplier(java.lang.String value);

        java.math.BigDecimal getLength();

        void setLength(java.math.BigDecimal value);

        java.math.BigDecimal getWidth();

        void setWidth(java.math.BigDecimal value);

        java.math.BigDecimal getThickness();

        void setThickness(java.math.BigDecimal value);

        java.math.BigDecimal getRebate();

        void setRebate(java.math.BigDecimal value);

        java.lang.String getStatus();

        void setStatus(java.lang.String value);

        java.lang.String getItemCode();

        void setItemCode(java.lang.String value);

    }

}
